<?php

namespace Modules\Core\Models;

use  \Illuminate\Database\Eloquent\Model;

/**
 * Eloquent class to describe the nix_pessoas table
 *
 * automatically generated by ModelGenerator.php
 */
class Teste extends Model
{

}
